name: Week
form: $/acornassociated/calendar/models/calendar/fields.yaml
modelClass: AcornAssociated\Calendar\Models\Calendar
defaultRedirect: acornassociated/calendar/week
create:
    redirect: 'acornassociated/calendar/week/update/:id'
    redirectClose: acornassociated/calendar/week
update:
    redirect: acornassociated/calendar/week
    redirectClose: acornassociated/calendar/week
