scopes:
    calendar:
        label: Calendar
        modelClass: AcornAssociated\Calendar\Models\Calendar
        conditions: (select ce.calendar_id from acornassociated_calendar_event ce where event_id = ce.id) in (:filtered)
        nameFrom: name
    date:
        label: Date Range
        type: daterange
        yearRange: 10
        # default: 0: now 1: +1 month
        conditions: date >= is_date(':after'::varchar, now()) AND date <= is_date(':before'::varchar, now() + interval '1 month')

    status:
        label: Status
        modelClass: AcornAssociated\Calendar\Models\Status
        conditions: (select ce.status_id from acornassociated_calendar_event ce where event_id = ce.id) in (:filtered)
        nameFrom: name

    type:
        label: Type
        modelClass: AcornAssociated\Calendar\Models\Type
        conditions: (select ce.type_id from acornassociated_calendar_event ce where event_id = ce.id) in (:filtered)
        nameFrom: name

    location:
        label: Location
        modelClass: AcornAssociated\Location\Models\Location
        conditions: (select ce.location_id from acornassociated_calendar_event ce where event_id = ce.id) in (:filtered)
        nameFrom: name

    groups:
        label: Groups
        modelClass: AcornAssociated\Calendar\Models\EventPart
        conditions: exists(select * from acornassociated_calendar_event_user_group ug where acornassociated_calendar_instance.event_id = ug.event_id and user_group_id in (:filtered))
        options: groupsAll

    users:
        label: Users
        modelClass: AcornAssociated\Calendar\Models\EventPart
        conditions: exists(select * from acornassociated_calendar_event_user u where acornassociated_calendar_instance.event_id = u.event_id and u.user_id in (:filtered))
        options: usersAll

    myevents:
        label: My Events
        type: checkbox
        conditions: (select owner_user_id from acornassociated_calendar_event e where acornassociated_calendar_instance.event_id = e.id) = :user

    myattendance:
        label: Attending
        type: checkbox
        conditions: :user in(select user_id from acornassociated_calendar_event_user u where acornassociated_calendar_instance.event_id = u.event_id) or exists(select * from acornassociated_calendar_event_user_group ug where acornassociated_calendar_instance.event_id = ug.event_id and ug.user_group_id in(:groups))
